# Generated by Django 4.2.1 on 2023-05-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='time_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='time_started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
