# Generated by Django 4.2.1 on 2023-05-31 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0002_manager_password'),
        ('Scheme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scheme.scheme')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Log.teacher')),
            ],
        ),
    ]
