# Generated by Django 4.2.1 on 2023-05-31 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scheme', '0002_recentscheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('pdf', models.FileField(default='vid.jpg', upload_to='TM/Scheme_doc', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scheme.scheme')),
            ],
        ),
    ]
