# Generated by Django 4.2.1 on 2023-05-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheme', '0003_video_passage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='slug',
        ),
    ]
