# Generated by Django 4.2.1 on 2023-06-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheme', '0003_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='thumb',
            field=models.ImageField(blank=True, default='Scheme_images/google-document-icon-free-png_r0pGceu.png', null=True, upload_to='Scheme_images'),
        ),
    ]
