# Generated by Django 4.2.1 on 2023-05-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheme', '0004_remove_scheme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
