# Generated by Django 4.2.1 on 2023-05-06 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheme', '0007_alter_image_image_alter_video_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passage',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='passage',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='passage',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='Scheme_images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Scheme_images'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='vid.jpg', upload_to='TM/Scheme_video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
