# Generated by Django 4.2.1 on 2023-05-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheme', '0008_rename_content_passage_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passage',
            old_name='image',
            new_name='thumb',
        ),
    ]
