# Generated by Django 4.2.1 on 2023-06-16 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheme', '0008_alter_image_image_alter_passage_thumb_alter_pdf_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Scheme_images'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='thumb',
            field=models.ImageField(blank=True, default='Scheme_images/google-document-icon-free-png_r0pGceu.png', null=True, upload_to='Scheme_images'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(default='vid.jpg', upload_to='TM/Scheme_doc', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='vid.jpg', upload_to='TM/Scheme_video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
