# Generated by Django 4.2.1 on 2023-06-16 14:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
        ('Scheme', '0009_alter_image_image_alter_passage_thumb_alter_pdf_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=3000)),
                ('meeting_id', models.CharField(max_length=3000)),
                ('passcode', models.CharField(max_length=1000)),
                ('topic', models.CharField(max_length=300)),
                ('duration', models.IntegerField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('join_url', models.CharField(max_length=3000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
            ],
        ),
    ]
