# Generated by Django 4.2.1 on 2023-06-17 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
        ('Scheme', '0010_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Course.grade'),
            preserve_default=False,
        ),
    ]
