# Generated by Django 4.2.1 on 2023-05-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheme', '0011_alter_image_image_alter_passage_thumb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('con', models.JSONField()),
            ],
        ),
    ]
