# Generated by Django 4.2.1 on 2023-05-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheme', '0012_slides'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slides',
            new_name='Slide',
        ),
    ]
