# Generated by Django 4.2.1 on 2023-05-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
