# Generated by Django 4.2.1 on 2023-05-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_remove_course_code_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='slug',
            new_name='abbreviation',
        ),
    ]
