# Generated by Django 4.2.1 on 2023-05-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_subject_remove_coursereview_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='courses',
            field=models.ManyToManyField(to='Course.subject'),
        ),
    ]
