# Generated by Django 4.2.1 on 2023-05-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Scheme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question_num', models.IntegerField(blank=True, default=10, null=True)),
                ('duration', models.IntegerField(help_text='Duration allowed for Quiz in minutes')),
                ('level', models.CharField(choices=[('easy', 'easy'), ('normal', 'normal'), ('difficult', 'difficult')], max_length=30)),
                ('con', models.JSONField(blank=True, null=True)),
                ('marking_scheme', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('completed', 'completed')], default='pending', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scheme.scheme')),
            ],
            options={
                'verbose_name_plural': 'quizes',
            },
        ),
    ]
