# Generated by Django 4.2.1 on 2023-05-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type',
            field=models.CharField(choices=[('test', 'test'), ('assignment', 'assignment')], default='assignment', max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], default='locked', max_length=50),
        ),
    ]
