# Generated by Django 4.2.1 on 2023-05-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_remove_quiz_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='name',
            new_name='title',
        ),
    ]
