# Generated by Django 4.2.1 on 2023-05-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_rename_name_quiz_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
