# Generated by Django 4.2.1 on 2023-05-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_quizsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='level',
        ),
    ]
