# Generated by Django 4.2.1 on 2023-05-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_remove_question_quiz_delete_answer_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='con',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
