# Generated by Django 4.2.1 on 2023-05-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_alter_quiz_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='marking_scheme',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
