# Generated by Django 4.2.1 on 2023-05-30 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_alter_quiz_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 12, 30, 10, 859738, tzinfo=datetime.timezone.utc)),
        ),
    ]
