# Generated by Django 4.2.1 on 2023-05-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='mark',
        ),
    ]
