# Generated by Django 4.2.1 on 2023-05-30 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_quiz_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
