# Generated by Django 4.2.1 on 2023-05-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_rename_score_score_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='choiceBox',
            new_name='choice_box',
        ),
    ]
