# Generated by Django 4.2.1 on 2023-05-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_alter_quiz_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration allowed for Quiz in minutes'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
