# Generated by Django 4.2.1 on 2023-05-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_rename_choicebox_score_choice_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='quiz',
        ),
        migrations.AddField(
            model_name='score',
            name='quiz_ans_box',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='quiz_con',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='quiz_title',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
