# Generated by Django 4.2.1 on 2023-05-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0011_remove_score_quiz_score_quiz_ans_box_score_quiz_con_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
