# Generated by Django 4.2.1 on 2023-06-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0011_assignment_assignmentsession_delete_curstudent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
    ]
