# Generated by Django 4.2.1 on 2023-06-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_quiz_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='question_num',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_num',
        ),
        migrations.DeleteModel(
            name='QuizSession',
        ),
    ]
