# Generated by Django 4.2.1 on 2023-06-06 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
        ('Quiz', '0014_remove_assignment_question_num_remove_quiz_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Course.course'),
            preserve_default=False,
        ),
    ]
