# Generated by Django 4.2.1 on 2023-06-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0015_assignment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='progress',
        ),
        migrations.AddField(
            model_name='assignment',
            name='protection',
            field=models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], default='locked', max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('completed', 'completed')], default='pending', max_length=20),
        ),
    ]
