# Generated by Django 4.2.1 on 2023-06-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0017_alter_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='con',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='marking_scheme',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='con',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='marking_scheme',
            field=models.JSONField(default=list),
        ),
    ]
