# Generated by Django 4.2.1 on 2023-06-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0002_manager_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='access_token',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
