# Generated by Django 4.2.1 on 2023-05-10 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0009_remove_grade_courses_course'),
        ('Log', '0003_alter_manager_course_alter_teacher_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.grade')),
            ],
        ),
        migrations.DeleteModel(
            name='LogBox',
        ),
    ]
