# Generated by Django 4.2.1 on 2023-05-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0004_student_delete_logbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
