# Generated by Django 4.2.1 on 2023-05-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0005_user_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='slug',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
