# Generated by Django 4.2.1 on 2023-05-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0006_manager_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
