# Generated by Django 4.2.1 on 2023-05-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0007_alter_manager_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='slug',
        ),
    ]
