# Generated by Django 4.2.1 on 2023-06-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grading',
            name='grades',
        ),
        migrations.AddField(
            model_name='grading',
            name='grade',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grading',
            name='max_mark',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grading',
            name='min_mark',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grading',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
