# Generated by Django 4.2.1 on 2023-06-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperManager', '0003_grading_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grading',
            name='max_mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='grading',
            name='min_mark',
            field=models.IntegerField(),
        ),
    ]
