# Generated by Django 4.2.1 on 2023-06-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperManager', '0007_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='salmon', max_length=300),
        ),
    ]
