# Generated by Django 4.2.1 on 2023-06-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
        ('SuperManager', '0009_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='grade',
            field=models.ManyToManyField(to='Course.grade'),
        ),
    ]
