# Generated by Django 4.2.1 on 2023-05-17 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Log', '0008_remove_manager_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=300)),
                ('quiz_con', models.JSONField(blank=True, null=True)),
                ('quiz_ans_box', models.JSONField(blank=True, null=True)),
                ('mark', models.FloatField()),
                ('choice_box', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Log.student')),
            ],
        ),
    ]
