# Generated by Django 4.2.1 on 2023-05-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_quizsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizSession',
        ),
    ]
