# Generated by Django 4.2.1 on 2023-05-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_alter_studentprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_pic',
        ),
    ]
