# Generated by Django 4.2.1 on 2023-05-17 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_delete_score'),
        ('Student', '0004_remove_studentprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='quiz_title',
        ),
        migrations.AddField(
            model_name='score',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz'),
            preserve_default=False,
        ),
    ]
