# Generated by Django 4.2.1 on 2023-05-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_schemeprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeprogress',
            name='progress_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
