# Generated by Django 4.2.1 on 2023-05-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_remove_score_quiz_title_score_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='slug',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
