# Generated by Django 4.2.1 on 2023-05-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_alter_schemeprogress_progress_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeprogress',
            name='progress_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
