# Generated by Django 4.2.1 on 2023-05-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_score_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='slug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
