# Generated by Django 4.2.1 on 2023-05-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_schemeprogress_progress_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeprogress',
            name='progress_count',
            field=models.FloatField(),
        ),
    ]
