# Generated by Django 4.2.1 on 2023-05-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_alter_score_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
            ],
        ),
    ]
