# Generated by Django 4.2.1 on 2023-05-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_curstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurStudent',
        ),
    ]
