# Generated by Django 4.2.1 on 2023-05-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_studentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='report',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
