# Generated by Django 4.2.1 on 2023-05-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0008_remove_manager_slug'),
        ('Student', '0012_alter_studentreport_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Log.student'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Log.student'),
        ),
    ]
