# Generated by Django 4.2.1 on 2023-05-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_alter_studentprofile_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
