# Generated by Django 4.2.1 on 2023-06-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0015_alter_schemeprogress_progress_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeprogress',
            name='progress_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
