# Generated by Django 4.2.1 on 2023-06-02 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
        ('Scheme', '0004_alter_passage_thumb'),
        ('Student', '0016_alter_schemeprogress_progress_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Course.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Scheme.scheme'),
            preserve_default=False,
        ),
    ]
