# Generated by Django 4.2.1 on 2023-06-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0017_score_course_score_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='slug',
        ),
    ]
