# Generated by Django 4.2.1 on 2023-06-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheme', '0004_alter_passage_thumb'),
        ('Course', '0001_initial'),
        ('Quiz', '0014_remove_assignment_question_num_remove_quiz_progress_and_more'),
        ('Log', '0002_manager_password'),
        ('Student', '0018_remove_score_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='QuizScore',
        ),
    ]
