# Generated by Django 4.2.1 on 2023-06-06 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scheme', '0004_alter_passage_thumb'),
        ('Log', '0002_manager_password'),
        ('Quiz', '0015_assignment_course'),
        ('Course', '0001_initial'),
        ('Student', '0019_rename_score_quizscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_con', models.JSONField(blank=True, null=True)),
                ('quiz_ans_box', models.JSONField(blank=True, null=True)),
                ('mark', models.FloatField()),
                ('choice_box', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scheme.scheme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Log.student')),
            ],
        ),
    ]
