# Generated by Django 4.2.1 on 2023-06-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0020_assignmentscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentscore',
            old_name='quiz_ans_box',
            new_name='ans_box',
        ),
        migrations.RenameField(
            model_name='assignmentscore',
            old_name='quiz_con',
            new_name='con',
        ),
        migrations.RenameField(
            model_name='assignmentscore',
            old_name='assignment',
            new_name='holder',
        ),
        migrations.RenameField(
            model_name='quizscore',
            old_name='quiz_ans_box',
            new_name='ans_box',
        ),
        migrations.RenameField(
            model_name='quizscore',
            old_name='quiz_con',
            new_name='con',
        ),
        migrations.RenameField(
            model_name='quizscore',
            old_name='quiz',
            new_name='holder',
        ),
    ]
