# Generated by Django 4.2.1 on 2023-06-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0021_rename_quiz_ans_box_assignmentscore_ans_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeprogress',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
